In [14]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from meteostat import Point, Daily, Hourly
from datetime import datetime
from geopy.geocoders import Nominatim
import os

In [15]:
pd.set_option('display.max_columns', None)

In [16]:
df_Msc_Ya = pd.read_csv('../data/Moscow_Yandex_10.csv', sep=',', index_col='date')
df_Msc_Ya

,day1,day2,day3,day4,day5,day6,day7,day8,day9,day10,night1,night2,night3,night4,night5,night6,night7,night8,night9,night10,weather1,weather2,weather3,weather4,weather5,weather6,weather7,weather8,weather9,weather10
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-05-15,18,20,19,18,20,21,19,15,15,14,8,14,10,8,10,13,9,7,7,8,Облачно с прояснениями,Небольшой дождь,Облачно с прояснениями,Ясно,Ясно,Ясно,Облачно с прояснениями,Ясно,Ясно,Облачно с прояснениями
2024-05-16,21,21,19,21,22,22,21,19,20,22,14,10,9,11,13,12,10,8,11,11,Небольшой дождь,Облачно с прояснениями,Ясно,Ясно,Облачно с прояснениями,Облачно с прояснениями,Облачно с прояснениями,Ясно,Ясно,Облачно с прояснениями
2024-05-17,21,19,20,24,23,24,21,20,24,19,10,9,11,13,13,13,10,12,14,11,Облачно с прояснениями,Ясно,Ясно,Ясно,Облачно с прояснениями,Ясно,Ясно,Ясно,Ясно,Облачно с прояснениями
2024-05-18,19,20,24,23,22,21,21,22,23,22,10,11,15,13,11,10,11,12,13,10,Ясно,Ясно,Ясно,Небольшой дождь,Облачно с прояснениями,Ясно,Ясно,Ясно,Облачно с прояснениями,Облачно с прояснениями
2024-05-19,21,24,24,24,19,21,24,23,23,23,11,15,14,11,8,10,14,13,13,14,Ясно,Ясно,Небольшой дождь,Ясно,Ясно,Ясно,Ясно,Ясно,Ясно,Облачно с прояснениями
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-25,24,22,21,21,18,13,19,22,20,15,14,16,16,19,11,9,11,12,11,9,Малооблачно,Пасмурно,Дождь,Дождь,Небольшой дождь,Небольшой дождь,Облачно с прояснениями,Пасмурно,Небольшой дождь,Пасмурно
2024-09-26,22,21,20,18,14,21,21,16,14,16,16,16,17,10,9,12,13,11,8,11,Пасмурно,Небольшой дождь,Дождь,Ливень,Пасмурно,Облачно с прояснениями,Небольшой дождь,Дождь,Небольшой дождь,Пасмурно
2024-09-27,20,21,19,12,19,22,20,13,14,18,15,17,10,9,13,13,12,8,8,11,Дождь,Небольшой дождь,Пасмурно,Пасмурно,Малооблачно,Ясно,Малооблачно,Дождь,Облачно с прояснениями,Пасмурно
2024-09-28,22,20,12,16,20,22,15,12,11,10,17,10,9,10,10,11,8,7,8,6,Дождь,Пасмурно,Пасмурно,Ясно,Облачно с прояснениями,Облачно с прояснениями,Пасмурно,Небольшой дождь,Облачно с прояснениями,Пасмурно
2024-09-29,20,12,15,20,19,15,15,13,15,15,11,9,10,12,10,9,8,8,11,11,Пасмурно,Пасмурно,Малооблачно,Облачно с прояснениями,Пасмурно,Пасмурно,Облачно с прояснениями,Малооблачно,Дождь,Дождь

In [17]:
df_Msc_Gis = pd.read_csv('../data/Moscow_GisMeteo_10.csv', sep=',', index_col='date')
df_Msc_Gis

,day1,day2,day3,day4,day5,day6,day7,day8,day9,day10,night1,night2,night3,night4,night5,night6,night7,night8,night9,night10,weather1,weather2,weather3,weather4,weather5,weather6,weather7,weather8,weather9,weather10
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-05-15,9,21,20,19,20,21,20,17,18,20,7,8,13,9,8,9,12,9,7,9,Облачно с прояснениями,Облачно с прояснениями,Небольшой дождь,Ясно,Ясно,Ясно,Небольшой дождь,Ясно,Ясно,Облачно с прояснениями
2024-05-16,20,21,20,21,21,21,21,17,15,16,5,14,9,9,11,12,12,12,6,7,Облачно с прояснениями,Небольшой дождь,Ясно,Ясно,Ясно,Небольшой дождь,Небольшой дождь,Дождь,Облачно с прояснениями,Облачно с прояснениями
2024-05-17,21,20,20,23,24,25,22,21,23,23,12,10,10,10,14,15,14,13,13,15,Дождь,Ясно,Ясно,Ясно,Небольшой дождь,Небольшой дождь,Дождь,Ясно,Облачно с прояснениями,Гроза
2024-05-18,20,20,23,23,23,21,21,23,21,17,10,10,11,14,14,13,13,14,14,12,Ясно,Ясно,Ясно,Гроза,Ясно,Ясно,Облачно с прояснениями,Облачно с прояснениями,Ясно,Дождь
2024-05-19,21,25,25,24,19,21,23,25,23,22,10,12,14,14,10,9,12,14,15,16,Ясно,Ясно,Гроза,Небольшой дождь,Ясно,Ясно,Ясно,Ясно,Облачно с прояснениями,Облачно
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-25,23,22,20,21,22,14,21,21,17,16,7,13,17,16,15,12,11,11,13,11,Ясно,"Облачно, без осадков","Пасмурно, дождь","Пасмурно, сильный дождь","Пасмурно, дождь","Пасмурно, дождь","Малооблачно, без осадков","Малооблачно, без осадков","Пасмурно, небольшой дождь","Пасмурно, небольшой дождь"
2024-09-26,22,22,21,20,17,21,20,21,16,19,14,16,17,16,12,10,10,11,12,12,"Малооблачно, без осадков","Пасмурно, небольшой дождь","Пасмурно, дождь","Пасмурно, дождь","Пасмурно, небольшой дождь","Малооблачно, без осадков","Малооблачно, без осадков","Малооблачно, небольшой дождь","Пасмурно, небольшой дождь","Облачно, небольшой дождь"
2024-09-27,20,22,21,15,20,22,17,14,12,13,16,16,16,11,10,12,12,12,8,7,"Облачно, дождь","Пасмурно, небольшой дождь","Пасмурно, небольшой дождь","Пасмурно, небольшой дождь","Облачно, без осадков","Малооблачно, без осадков","Облачно, без осадков","Пасмурно, дождь","Малооблачно, небольшой дождь","Облачно, без осадков"
2024-09-28,21,21,14,16,20,20,16,13,13,14,16,16,11,10,10,12,12,8,7,8,"Пасмурно, дождь","Пасмурно, дождь","Пасмурно, без осадков","Малооблачно, без осадков",Ясно,"Малооблачно, без осадков","Пасмурно, небольшой дождь","Малооблачно, без осадков","Пасмурно, без осадков","Облачно, небольшой дождь"
2024-09-29,20,14,14,20,18,14,15,18,17,19,14,11,9,9,12,10,9,9,13,13,"Облачно, небольшой дождь","Пасмурно, без осадков","Пасмурно, небольшой дождь","Малооблачно, без осадков","Малооблачно, без осадков","Облачно, без осадков","Малооблачно, без осадков","Малооблачно, без осадков","Пасмурно, без осадков","Пасмурно, без осадков"

In [18]:
full_date_range = pd.date_range(start=df_Msc_Gis.index.min(), end=df_Msc_Gis.index.max(), freq='D')
missing_dates = full_date_range.difference(df_Msc_Gis.index)
missing_dates

DatetimeIndex(['2024-06-27', '2024-06-28', '2024-06-29', '2024-08-04'], dtype='datetime64[ns]', freq=None)

In [28]:
def get_city_coordinates(city_name):
    geolocator = Nominatim(user_agent="weather_data_fetcher")
    location = geolocator.geocode(city_name)
    return location.latitude, location.longitude

city_name = "Moscow"
latitude, longitude = get_city_coordinates(city_name)

start = datetime(2024, 5, 15)
end = datetime(2024, 10, 8)


location = Point(latitude, longitude)

df2 = Daily(location, start, end)
df2 = df2.fetch()

df2.drop(index=['2024-06-27', '2024-06-28', '2024-06-29', '2024-08-04'], inplace=True)
df2

            tavg  tmin  tmax  prcp  snow   wdir  wspd  wpgt    pres  tsun
time
2024-05-15  10.8   4.3  15.9   0.0   NaN  358.0   1.4   NaN  1025.5   NaN
2024-05-16  13.8   5.0  20.1   0.6   NaN  286.0   2.2   NaN  1022.6   NaN
2024-05-17  16.2  11.8  20.8   4.1   NaN  355.0   5.0   NaN  1016.5   NaN
2024-05-18  14.9  10.0  20.0   0.0   NaN   41.0   3.6   NaN  1020.0   NaN
2024-05-19  14.9   9.4  19.6   0.0   NaN  133.0   3.0   NaN  1019.4   NaN
...          ...   ...   ...   ...   ...    ...   ...   ...     ...   ...
2024-10-04  12.3   8.7  15.6   NaN   NaN  123.0   1.0   NaN  1014.1   NaN
2024-10-05  11.4   9.0  13.7   NaN   NaN  343.0   2.2   NaN  1015.6   NaN
2024-10-06  10.1   7.0  13.3   NaN   NaN   28.0   2.7   NaN  1019.2   NaN
2024-10-07  10.4   7.8  13.2   NaN   NaN   56.0   2.1   NaN  1016.6   NaN
2024-10-08  11.3   8.9  14.1   NaN   NaN  353.0   2.4   NaN  1014.0   NaN

[143 rows x 10 columns]

In [29]:
df_night = df2.iloc[:,1].values
df_night_real = []

for i in range(len(df_night)-10+1):
    df_night_real.append(df_night[i:i+10])

df_night_real = np.array(df_night_real)
df_night_real

array([[ 4.3,  5. , 11.8, ..., 12.1, 10.4,  9.2],
       [ 5. , 11.8, 10. , ..., 10.4,  9.2, 10. ],
       [11.8, 10. ,  9.4, ...,  9.2, 10. , 11. ],
       ...,
       [14.5, 14.9, 11.8, ...,  8.7,  9. ,  7. ],
       [14.9, 11.8,  8.4, ...,  9. ,  7. ,  7.8],
       [11.8,  8.4,  7.3, ...,  7. ,  7.8,  8.9]])

In [30]:
df_day = df2.iloc[:,2].values
df_day_real = []

for i in range(len(df_day)-10+1):
    df_day_real.append(df_day[i:i+10])

df_day_real = np.array(df_day_real)
df_day_real

array([[15.9, 20.1, 20.8, ..., 22.6, 20. , 21.5],
       [20.1, 20.8, 20. , ..., 20. , 21.5, 23.9],
       [20.8, 20. , 19.6, ..., 21.5, 23.9, 24.3],
       ...,
       [20.2, 22.3, 19.4, ..., 15.6, 13.7, 13.3],
       [22.3, 19.4, 12.9, ..., 13.7, 13.3, 13.2],
       [19.4, 12.9, 16.7, ..., 13.3, 13.2, 14.1]])

In [31]:
df_msc_ya_day = df_Msc_Ya.iloc[:,:10].values
df_msc_ya_day

array([[18, 20, 19, ..., 15, 15, 14],
       [21, 21, 19, ..., 19, 20, 22],
       [21, 19, 20, ..., 20, 24, 19],
       ...,
       [20, 21, 19, ..., 13, 14, 18],
       [22, 20, 12, ..., 12, 11, 10],
       [20, 12, 15, ..., 13, 15, 15]], dtype=int64)

In [32]:
df_msc_ya_night = df_Msc_Ya.iloc[:,10:20].values
df_msc_ya_night

array([[ 8, 14, 10, ...,  7,  7,  8],
       [14, 10,  9, ...,  8, 11, 11],
       [10,  9, 11, ..., 12, 14, 11],
       ...,
       [15, 17, 10, ...,  8,  8, 11],
       [17, 10,  9, ...,  7,  8,  6],
       [11,  9, 10, ...,  8, 11, 11]], dtype=int64)

In [33]:
df_msc_gis_day = df_Msc_Gis.iloc[:,:10].values
df_msc_gis_day

array([[ 9, 21, 20, ..., 17, 18, 20],
       [20, 21, 20, ..., 17, 15, 16],
       [21, 20, 20, ..., 21, 23, 23],
       ...,
       [20, 22, 21, ..., 14, 12, 13],
       [21, 21, 14, ..., 13, 13, 14],
       [20, 14, 14, ..., 18, 17, 19]], dtype=int64)

In [34]:
df_msc_gis_night = df_Msc_Gis.iloc[:,10:20].values
df_msc_gis_night

array([[ 7,  8, 13, ...,  9,  7,  9],
       [ 5, 14,  9, ..., 12,  6,  7],
       [12, 10, 10, ..., 13, 13, 15],
       ...,
       [16, 16, 16, ..., 12,  8,  7],
       [16, 16, 11, ...,  8,  7,  8],
       [14, 11,  9, ...,  9, 13, 13]], dtype=int64)

In [48]:
list_mae_day_ya = []
list_mae_day_gis = []

for i in range(10):
    mae_day_ya = np.mean(np.abs(df_day_real[:, i] - df_msc_ya_day[:, i]))
    mae_day_gis = np.mean(np.abs(df_day_real[:, i] - df_msc_gis_day[:, i]))

    list_mae_day_ya.append(mae_day_ya)
    list_mae_day_gis.append(mae_day_gis)

    print(f'MAE for Day Yandex {i+1:<2}: {mae_day_ya:<6.4f} \t\t| MAE for Day GisMeteo {i+1:<2}: {mae_day_gis:<6.4f}')

print(f"Day Yandex: {np.mean(np.array(list_mae_day_ya)):<6.4f} \t\t\t| Day GisMeteo: {np.mean(np.array(list_mae_day_gis)):<6.4f}")

MAE for Day Yandex 1 : 0.8679 		| MAE for Day GisMeteo 1 : 0.8351
MAE for Day Yandex 2 : 0.8007 		| MAE for Day GisMeteo 2 : 0.9112
MAE for Day Yandex 3 : 0.9649 		| MAE for Day GisMeteo 3 : 1.1619
MAE for Day Yandex 4 : 1.1306 		| MAE for Day GisMeteo 4 : 1.1933
MAE for Day Yandex 5 : 1.3612 		| MAE for Day GisMeteo 5 : 1.5388
MAE for Day Yandex 6 : 1.4776 		| MAE for Day GisMeteo 6 : 1.5866
MAE for Day Yandex 7 : 1.7030 		| MAE for Day GisMeteo 7 : 1.8343
MAE for Day Yandex 8 : 2.1433 		| MAE for Day GisMeteo 8 : 2.2209
MAE for Day Yandex 9 : 2.2433 		| MAE for Day GisMeteo 9 : 2.8254
MAE for Day Yandex 10: 2.7306 		| MAE for Day GisMeteo 10: 3.2276
Day Yandex: 1.5423 			| Day GisMeteo: 1.7335

In [49]:
list_mae_night_ya = []
list_mae_night_gis = []

for i in range(10):
    mae_night_ya = np.mean(np.abs(df_night_real[:, i] - df_msc_ya_night[:, i]))
    mae_night_gis = np.mean(np.abs(df_night_real[:, i] - df_msc_gis_night[:, i]))

    list_mae_night_ya.append(mae_night_ya)
    list_mae_night_gis.append(mae_night_gis)

    print(f'MAE for Night Yandex {i+1:<2}: {mae_night_ya:<6.4f} \t| MAE for Night GisMeteo {i+1:<2}: {mae_night_gis:<6.4f}')

print(f"Night Yandex: {np.mean(np.array(list_mae_night_ya)):<6.4f} \t\t\t| Night GisMeteo: {np.mean(np.array(list_mae_night_gis)):<6.4f}")

MAE for Night Yandex 1 : 2.0836 	| MAE for Night GisMeteo 1 : 0.6269
MAE for Night Yandex 2 : 2.1828 	| MAE for Night GisMeteo 2 : 2.2963
MAE for Night Yandex 3 : 2.1030 	| MAE for Night GisMeteo 3 : 2.3687
MAE for Night Yandex 4 : 2.0515 	| MAE for Night GisMeteo 4 : 2.5709
MAE for Night Yandex 5 : 2.0709 	| MAE for Night GisMeteo 5 : 2.5291
MAE for Night Yandex 6 : 2.0851 	| MAE for Night GisMeteo 6 : 2.7537
MAE for Night Yandex 7 : 2.0836 	| MAE for Night GisMeteo 7 : 2.7119
MAE for Night Yandex 8 : 2.2410 	| MAE for Night GisMeteo 8 : 3.0888
MAE for Night Yandex 9 : 2.3672 	| MAE for Night GisMeteo 9 : 3.0403
MAE for Night Yandex 10: 2.4142 	| MAE for Night GisMeteo 10: 3.0634
Night Yandex: 2.1683 			| Night GisMeteo: 2.5050